### ISSUE TITLE
Share WiFi internet with static IP on ethernet switch?

### ISSUE THREAD

**Issue by cmcmurrough** [arpitjindal97/raspbian-recipes#10]
Thanks for posting your eth-to-wifi-route.sh script, much appreciated!

Is there a way to modify this such that the internet connection is shared with a specific static IP on the ethernet side? Specifically what I want to do is have a device with static IP on the same unmanaged network switch as the Pi access the internet through the Pi's WiFi, but I don't want any of the other devices to be able to do the same. I have both the Pi and the target device set up with static IPs on the swtich. 

Any ideas?

**Comment by arpitjindal97** [comment]
Do you mean [wifi-to-eth-route.sh](https://github.com/arpitjindal97/raspbian-recipes/blob/master/wifi-to-eth-route.sh) script ? Because the workaround you specified doesn't fit with [eth-to-wifi-route.sh](https://github.com/arpitjindal97/raspbian-recipes/blob/master/eth-to-wifi-route.sh) .

**Comment by cmcmurrough** [comment]
Yes, my mistake.

In that example, you are using DHCP to automatically assign an IP address to the ethernet client. In my setup, I have many ethernet clients connected through a switch but only want to grant internet access to a single static IP.

Thank you for your help!

**Comment by arpitjindal97** [comment]
Add these rules after the existing rules in the script

    sudo iptables -I INPUT -i eth0 -p tcp -s 0.0.0.0 -j REJECT
    sudo iptables -I INPUT -i eth0 -p tcp -s $client_ip_with_internet -j ACCEPT
    sudo iptables -I OUTPUT -i eth0 -p tcp -d  $client_ip_with_internet -j ACCEPT

replace `$client_ip_with_internet` with **IP Address of the client** you want to provide internet access or set the variables in the beginning of the script

See if it works. If doesn't then give me some time to provide correct solution

**Comment by arpitjindal97** [comment]
Closing it for being inactive for long. Re-open again if your problem is not yet solved
