### ISSUE TITLE
Autostart without LXDE

### ISSUE THREAD

**Issue by ghost** [arpitjindal97/raspbian-recipes#11]
https://raspberrypi.stackexchange.com/a/8735/86894 might be of help. I'm using raspian lite so there's no desktop to run a script at startup.

**Comment by arpitjindal97** [comment]
Look at this issue #1 

Maybe you can create a PR adding these details in README

**Comment by ghost** [comment]
Sorry I missed that. Solution worked just fine and is very elegant. You're a wizard. Thanks.
