### ISSUE TITLE
wifi-to-eth-route.sh via rc.local fails if network not ready

### ISSUE THREAD

**Issue by jamielaundon** [arpitjindal97/raspbian-recipes#14]
Thanks for these amazing scripts, they've come in very handy.

I had a problem where if I launch these via rc.local, it fails because the network isn't ready yet.
A quick workaround is to add

```
sleep 20
```

I've found a better way so that the script is fired when the network comes up:

```
sudo nano /etc/systemd/system/wifi-to-eth.service
```

```
[Unit]
Description=Wifi to Eth Route
After=network.target

[Service]
Type=oneshot
ExecStart=/home/pi/wifi-to-eth-route.sh
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
```

Then

```
sudo systemctl enable /etc/systemd/system/wifi-to-eth.service
```

The magic is the _After=network.target_

On screen during boot we see
```
[  OK  ] Started Raise network interfaces.
[  OK  ] Reached target Network.
         Starting dnsmasq - A lightweight DHCP and caching DNS server...
         Starting Permit User Sessions...
         Starting Wifi to Eth Route...
         Starting /etc/rc.local Compatibility...
         Starting OpenBSD Secure Shell server...
```

**Comment by arpitjindal97** [comment]
It's a very good idea to create a service for script. 

Take some time and create a PR, lets see if we can make it more easy
