### ISSUE TITLE
Script For Wifi to wifi

### ISSUE THREAD

**Issue by saikhurana** [arpitjindal97/raspbian-recipes#17]
Hey arpit,
i have really liked using your scripts but now i want to request a new script. like. a wifi to wifi route and bridge. For example using wlan0 as a wifi client and wlan1 as an Access Point. using hostapd or some similar. also please make sure so that the script work with default raspbian network utility and Network Manager. if you can add support for pihole, that would be just perfect.

**Comment by arpitjindal97** [comment]
Try the new script. It should work with default raspbian network utility. 

 - Raspberry Pi's wifi chip is being used as Hotspot because it was giving good speed
 - USB Adaper wifi is used for connecting to Wi-Fi Router for internet access
