### ISSUE TITLE
Modify to use as Gateway

### ISSUE THREAD

**Issue by stevemac00** [arpitjindal97/raspbian-recipes#2]
Your wifi-to-eth-route.sh works well. Thank you for posting as iptables baffle me.

Would you consider modifications to a new script to provide the pi as a gateway?

Specifically, I'd like the pi3 wifi to connect and pass the gateway ip to the eth port to connect to a router (pfSense). One could then use a MiFi or any alternate wifi connection as a failover or load balancing connection to internet. I think this means to skip the DHCP and be a bridge so the wifi network ip address is assigned to the [pfSense] connected to the eth port.

I found other attempts at this but they all modify network/interfaces and/or other hacks and I could not get them to work for me on debian stretch. (Is a WDS required? I read something about 4-address/3-address transferring from wlan to eth.)

**Comment by arpitjindal97** [comment]
You can't bridge wlan0 with eth0 (internet source is wlan0) even if the WiFi chip supports 4addr. 

Raspberry Pi 3 chip doesn't support 4addr but i have even tried it with a USB WiFi adapter which supports 4addr. A better explanation is [here](https://raspberrypi.stackexchange.com/questions/51057/raspberry-pi-3-model-b-wireless-bridge-to-ethernet#55731).

Real Layer 2 bridging is not possible at all in this case. I tried experimenting with `ebtables` also but  it didn't work out. NAT/Route is the only possible way to do it. 

You can however do vice-versa, bridge eth0 with wlan0 (internet source eth0). Other devices will connect to RPi Hotspot and will get the IP address directly from router.

**Comment by stevemac00** [comment]
Thanks. You're far more knowledgeable than I so I should take your advice and stop trying.
But then I read about a Layer 3 solution using proxy arp for this very purpose.
https://wiki.debian.org/BridgeNetworkConnectionsProxyArp
I get the Pi3 wlan0 connected to wifi hotspot and it's net address is also shown on eth0 but my pfSense doesn't get the local IP of the Pi so I'm stuck.

**Comment by arpitjindal97** [comment]
So, I have made this small script to automate Proxy ARP. I have tried it on my Raspberry Pi. Hosts connected to RPi on Ethernet side are getting IP addresses .

Verify the steps you did manually with those in my script. 

I couldn't get `avahi-daemon` to get started on boot yet, I will fix that soon. Till then, try this and let me know if something is missing.

**Comment by stevemac00** [comment]
I appreciate your effort. I couldn't get it to work. I have internet on pi but host cannot connect on eth0 as it cannot get an IP address. I attached the script output as well as `ifconfig`.

```
root@wifigate:/home/pi# ./wifi-to-eth-bridge.sh
dhcp-helper: no process found
Warning: Stopping avahi-daemon.service, but it can still be activated by:
  avahi-daemon.socket
avahi-daemon: no process found
dhcp-helper: cannot bind DHCP server socket: Address already in use
root@wifigate:/home/pi# Process 1538 died: No such process; trying to remove PID file. (/var/run/avahi-daemon//pid)
Found user 'avahi' (UID 108) and group 'avahi' (GID 112).
Successfully dropped root privileges.
avahi-daemon 0.6.32 starting up.
Successfully called chroot().
Successfully dropped remaining capabilities.
No service file found in /etc/avahi/services.
Joining mDNS multicast group on interface wlan0.IPv6 with address fe80::11d3:aaf1:1e21:203d.
New relevant interface wlan0.IPv6 for mDNS.
Joining mDNS multicast group on interface wlan0.IPv4 with address 10.234.77.129.
New relevant interface wlan0.IPv4 for mDNS.
Joining mDNS multicast group on interface eth0.IPv4 with address 10.234.77.129.
New relevant interface eth0.IPv4 for mDNS.
Network interface enumeration completed.
Registering new address record for fe80::11d3:aaf1:1e21:203d on wlan0.*.
Registering new address record for 10.234.77.129 on wlan0.IPv4.
Registering new address record for 10.234.77.129 on eth0.IPv4.
Server startup complete. Host name is wifigate.local. Local service cookie is 1503593584.

root@wifigate:/home/pi# ifconfig -a
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.234.77.129  netmask 255.255.255.255  broadcast 0.0.0.0
        ether b8:27:eb:16:91:96  txqueuelen 1000  (Ethernet)
        RX packets 46  bytes 17244 (16.8 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 302  bytes 26843 (26.2 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 27  bytes 2154 (2.1 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 27  bytes 2154 (2.1 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.234.77.129  netmask 255.224.0.0  broadcast 10.255.255.255
        inet6 fe80::11d3:aaf1:1e21:203d  prefixlen 64  scopeid 0x20<link>
        ether b8:27:eb:43:c4:c3  txqueuelen 1000  (Ethernet)
        RX packets 143  bytes 18856 (18.4 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 753  bytes 89454 (87.3 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

root@wifigate:/home/pi# Withdrawing address record for 10.234.77.129 on eth0.
Leaving mDNS multicast group on interface eth0.IPv4 with address 10.234.77.129.
Interface eth0.IPv4 no longer relevant for mDNS.

```

**Comment by arpitjindal97** [comment]
The problem is on this line
```
dhcp-helper: cannot bind DHCP server socket: Address already in use
```

`dhcp-helper` uses UDP Port 67, it looks like some other process is already using this port before `dhcp-helper` is started. 

You can list all the port being used and their respective program name with pid.
```
sudo netstat -tulpn
```
Find the process name and kill it, you must have installed some package which is using this port. 
or Try it on **fresh** Raspbian Stretch Image and it will work fine.

**Comment by stevemac00** [comment]
I see what you're referring to about dhcp-helper port in use. That was from dnsmasq in earlier scripts so I did fresh install of 2017-11-29-raspbian-stretch-desktop.img
sudo apt-get install parprouted dhcp-helper
configured wpa-supplicant.conf
reboot - wifi connects fine
run wifi-to-eth-bridge.sh
As before, ifconfig shows wifi inet address but the eth0 attached host gets a link address of 169.254.117.137
I tried everything I could. (I also noticed after a minute of so, the mdns relinqushed the addresses.)

**Comment by arpitjindal97** [comment]
`dhcp-helper` is responsible for assigning IP addresses to devices connected to `eth0`. 

`mdns` is related to `avahi-daemon`, we don't need it as of now. Follow these steps 

- Comment the last line which will start `avahi-daemon` in the script. 
- Comment `dhcp-helper` line also
- Run the script
- type this command manually, it should execute successfully

      sudo /usr/sbin/dhcp-helper -r /var/run/dhcp-helper.pid -b wlan0 

Now check if LAN device is getting IP address or not.

**Comment by arpitjindal97** [comment]
I was trying this script with my another router and found that it wasn't working.

Same script working with one router but not with another. There must be some sort of security in router firmware which doesn't let Wi-Fi to bridge.
