### ISSUE TITLE
wifi to eth not working

### ISSUE THREAD

**Issue by gitkav** [arpitjindal97/raspbian-recipes#20]
Hi Arpit 

I have rapberry VERSION="9 (stretch)"
I tried your script wifi-to-eth-route.sh, but unfortunately its not working for me.
The device that wants to use the raspberry wifi connection is a TV.
I have connected the TV to raspberry pi through LAN cable and ran you script on reboot.
My network interface file is

My /etc/wpa_supplicant/wpa_supplicant.conf has
country=GB
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
network={
    ssid="Home WiFi"
    psk="password_goes_here"
}

Can you please let me know what I am missing

The TV got an ip adress but its not connected to internet

**Comment by arpitjindal97** [comment]
try this one: 

```
country=GB
ctrl_interface=/var/run/wpa_supplicant
update_config=1
network={
ssid="Home WiFi"
psk="password_goes_here"
}
```

**Comment by arpitjindal97** [comment]
Thanks for notifying. I will fix the README with correct config.

**Comment by gitkav** [comment]
Hi Arpit,

The TV show not connected but when I open a http link on a browser it works. When I try to access any https link I see a security message. Also I took the tcp dump on raspeberry pi and found that Sony TV is rejecting TLS connections which are routed through raspi

**Comment by gitkav** [comment]
Its working now, the date and time on my tv was incorrect because of which TV was rejecting the TLS certificate. Thanks
