### ISSUE TITLE
Weird issue

### ISSUE THREAD

**Issue by strubelz** [arpitjindal97/raspbian-recipes#21]
Sorry for the lazy title, but I have a really weird issue, when using the wifi-to-eth-route script.
When my wpa_supplicants.conf looks like this, it doesn't work.

`country=DE`
`ctrl_interface=/var/run/wpa_supplicant`
`update_config=1`
`network={`
`    ssid="jwlan"`
`    psk="password_goes_here"`
`}`

Then I add these two lines, and it works.

`key_mgmt=WPA-EAP`
`eap=PEAP`

But now when I restart the Wifi won't connect. To make it work again I need to remove the two lines, restart, add the lines again and then rerun the script. I'm a total networking noob, so I have no idea whats causing this. I'm using the Raspberry Pi 3 and the newest version of Raspbian Stretch Lite.

**Comment by arpitjindal97** [comment]
This related to router. You have configured your router security to `WPA-EAP`. Set it to `WPA-PSK` and it will connect normally
