### ISSUE TITLE
Bridging WiFi Connection

### ISSUE THREAD

**Issue by schulz-m** [arpitjindal97/raspbian-recipes#25]
Not really an issue per se, but I hope it's the right forum to reach out.

The problem I am having is that I want to connect a NAS over WiFi that only has an Ethernet Interface and therefore thought about using the Raspberry Pi to bridge the WiFi connection.

The behavior I would prefer would basically be that from the NAS perspective, the Ethernet connects to the same network as the WiFi the Raspberry Pi is connected to.

I understand that the route script makes the Raspberry Pi act as a router of sorts - but then I don't know how to connect to the NAS as it's in an isolated local network as I understand. 

Would the [bridge](https://github.com/arpitjindal97/raspbian-recipes/blob/master/wifi-to-eth-bridge.sh) script serve the described purpose? (I didn't get it to work properly)

Thank you for the useful scripts!

**Comment by arpitjindal97** [comment]
You are on right track buddy, the wifi bridging is Layer 3 solution which doesn't work with some routers.

Follow below steps to check of bridging is working fine in your case or not

- Create Hotspot via phone
- Configure wpa_supplicant in RPi to connect to phone hotspot
- Put the bridging script in place
- Plug the ethernet cable to NAS
- Reboot Pi

The device on Eth side should get IP and in your phone you should see 2 devices connected. If this is not the case then we have to debug the problem
