### ISSUE TITLE
Failed to create interface

### ISSUE THREAD

**Issue by ArnoAurelien** [arpitjindal97/raspbian-recipes#27]
Hello !
I tried out your wifi to eth script, and it worked great !
I'm having trouble with this script though, when I run it, I get this:

Configuration file: /etc/hostapd/hostapd.conf
Failed to create interface mon.wlan0: -95 (Operation not supported)
wlan0: Could not connect to kernel driver
Using interface wlan0 with hwaddr b8:27:eb:88:3d:9f and ssid "Raspberry-Hotspot"
wlan0: interface state UNINITIALIZED->ENABLED
wlan0: AP-ENABLED

(and then from there the script never finishes, I think)

I googled "Failed to create interface mon.wlan0: -95 (Operation not supported)" to find solutions, but sadly I got nothing. What should I do, and where should I look ?

By the way: I'm a noob... so I can only follow instructions and understand with detailed explanation /:

Thanks !

**Comment by ArnoAurelien** [comment]
Hi again !

Actually, it works fine regardless of this error message.
Just for curiosity's sake: what is it ? Why is it showing up ?

Also: I run the script manually because I found no autostart file in /home/pi/.config/lxsession/LXDE-pi/

Where is it ?

Thanks !

**Comment by arpitjindal97** [comment]
If you are using Raspbian Lite version then `/home/pi/.config/lxsession/LXDE-pi/` won't be there. See #1 

For the errors thrown by the script. I haven't used my scripts in a while but as long as it's working it should be fine.
