### ISSUE TITLE
wifi-to-eth-route.sh with uap0

### ISSUE THREAD

**Issue by ZZerog** [arpitjindal97/raspbian-recipes#28]
Hi all.

I have a question on wifi-to-eth-route.sh script.

The script work really well. But when I try create virtual AP interface 

`iw dev wlan0 interface add uap0 type __ap`

and then start the script with that interface (uap0). The script work but dmesg get errors

`brcmfmac: brcmf_cfg80211_scan: scan error (-110)`

The AP go to DISABLE then to ENABLE then DISABLE ...

Thanks for your help

RPI 3B+, 4.14

**Comment by arpitjindal97** [comment]
I have never tried creating virtual interface. And virtual Interface won't work if there is something related to AP.

AP interface needs to available physically maybe that's why it's giving Broadcom chip erros because it's not able to find it

**Comment by ZZerog** [comment]
Hi.

Now the AP by uap0 interface is working. I edit your scripts and now do:
1. create uap0 interface
2. create AP on uap0
3. wlan0 is in the 'client mode' and is connected to a preferred network
4. forward packet from wlan0 to uap0

BUT I really don't know what  caused my issue :(.
