### ISSUE TITLE
Share USB tethering

### ISSUE THREAD

**Issue by jendib** [arpitjindal97/raspbian-recipes#3]
I used `wifi-to-eth-route.sh` to share the USB tethering from my Android phone by just swapping wlan0 for usb0 and it works perfectly. Thanks! 👍

**Comment by osokthedevil** [comment]
would this work the opposite way usb-to-wife-router? like tethering off your smart phone via usb? then again it would be easier to do the wifi-to-wifi-router.

**Comment by arpitjindal97** [comment]
You can try that, if it works then well and good
