### ISSUE TITLE
How configure second wlan?

### ISSUE THREAD

**Issue by rexy666** [arpitjindal97/raspbian-recipes#31]
Im using the bridge script on a rpi3b+. The one with an onboard wifi built in. I got the script working with it, but now I need to use a usb dongle. I can set the script to use wlan0 or wlan1 as needed. The problem is that I’m unable to configure the adapter in the first place. Anything I tried gives me an error or simply says it’s not associated. I’m assuming it’s because the script installs a second DHCP server or something. Please can someone point me out in the right direction?

**Comment by arpitjindal97** [comment]
Do one thing, before running any script just connect the usb wifi normally and try to connect it to your home wifi. Check if it getting connected and obtaining the IP address. 

Also, append the output of `ifconfig` before and after plugging the external usb wifi. 

Is it usb wifi or data dongle with sim card ?

**Comment by rexy666** [comment]
Sorry, you can close this thread. The issues had nothing to do with your script. Your script is amazing. Thanks for thaking the time of coding it and supporting it
