### ISSUE TITLE
/home/pi/.config/lxsession/LXDE-pi/autostart not present in ubuntu buster

### ISSUE THREAD

**Issue by Schizo** [arpitjindal97/raspbian-recipes#37]
Hi, 

I was trying to follow the walkthrough, however, figured that the folder doesn't exist for me:

```
    /home/pi/.config/lxsession/LXDE-pi/autostart
```

I'm not too familiar with raspbian, but is there another way adding it to autostart in `raspbian buster`?

**Comment by arpitjindal97** [comment]
The path of this autostart script depends on the Desktop Environment. In Raspbian, LXDE comes default, so above path is specific to LXDE.

Based on your DE you are using in ubuntu buster. you can configure it.

**Comment by Schizo** [comment]
Sorry, that's my bad I accidentally typed `ubuntu buster` instead of `raspbian buster`. Anyhow I finally switched to the lite version. Will see how it goes from there.

**Comment by Schizo** [comment]
I've used the lite version and it worked like a charm.
