### ISSUE TITLE
Benchmark about performance

### ISSUE THREAD

**Issue by Schizo** [arpitjindal97/raspbian-recipes#38]
Hi, 

I was wondering if there are any number's on how much bandwidth (loss) is happening when the raspberry is bridging the connection? In my case "wifi-to-eth". Are there any numbers on how much latency/bandwith decrease you get?

**Comment by arpitjindal97** [comment]
There aren't any benchmark. It depends on the Raspberry Pi how much load it can handle. It's a small device and gets heated very fast.
