### ISSUE TITLE
How to disable?

### ISSUE THREAD

**Issue by Noirad** [arpitjindal97/raspbian-recipes#4]
Hey, thanks for sharing this script and posting on this forum (https://raspberrypi.stackexchange.com/questions/48307/sharing-the-pis-wifi-connection-through-the-ethernet-port)!

At the moment, I’m trying to disable the feature to use Ethernet normally. 

Could you offer some advice about how to do so?

Any feedback would be greatly appreciated! 

Thanks so much!

**Comment by arpitjindal97** [comment]
Please explain what do you actually want to do ? How do you want to use Ethernet ?

**Comment by Noirad** [comment]
Hey @arpitjindal97, that is exactly what I'd like to do!

**Comment by Noirad** [comment]
Thanks for the swift reply, didn't see your notification!

**Comment by arpitjindal97** [comment]
I don't understand your question properly. Please explain a bit more. Are you trying to do exact same thing what the script does manually ? If yes, then you can just read the content of the script and understand what's going on under the hood.

**Comment by Noirad** [comment]
I'm trying to stop the script and connect my raspberry pi to the internet via Ethernet.

It looks like during boot the script is launched and the IP tables are forwarded.

If I remove the script from /home/pi and reboot, will I be able to connect my raspberry pi normally to Ethernet again?

I would simply this out, but I'm working on this unit remotely. I do have someone who can connect the Ethernet cable so I can confirm.

**Comment by arpitjindal97** [comment]
Yes, you can remove the script from `/home/pi` or just rename it and you will be able to use ethernet normally. 
These scripts are made to be dynamic, not a single files will be modified in your file system. 
Removing the script will restore the Pi to it's **original** state.

**Comment by Noirad** [comment]
Perfect, I'll give it a try today!

**Comment by arpitjindal97** [comment]
Is your problem solved now ?
