### ISSUE TITLE
Bridge using a vpn

### ISSUE THREAD

**Issue by marcocondrache** [arpitjindal97/raspbian-recipes#41]
Hello man! Your script works fine but i have a little problem.
I use openvpn to create a vpn connection to a provider.
When i create this connection a new interface is added but the internet connection stops working.
I think that happens because there is no bridge between the eth0 and the new interface.
How can i bridge the eth0 to the vpn interface and the new interface to the wlan0? Thank you for the help

**Comment by arpitjindal97** [comment]
Which interface is source of internet?

cc @saikhurana98

**Comment by marcocondrache** [comment]
The internet source is wlan0

**Comment by saikhurana98** [comment]
I'm not entirely sure but just use the virtual interface created by vpn as a source for your vpn'd internet.

**Comment by marcocondrache** [comment]
> I'm not entirely sure but just use the virtual interface created by vpn as a source for your vpn'd internet. 

Thank you I will try.

**Comment by marcocondrache** [comment]
> I'm not entirely sure but just use the virtual interface created by vpn as a source for your vpn'd internet. 

I tried it by changing the wlan variable inside the script with the name of the new interface created but the problem of internet absence has not been solved

**Comment by arpitjindal97** [comment]
You need to create 2 bridges:

 - wlan0 to vpn0
 - vpn0 to eth0

**Comment by marcocondrache** [comment]
> You need to create 2 bridges:
> 
> 
> 
>  - wlan0 to vpn0
> 
>  - vpn0 to eth0


if I'm not mistaken and from what I read online the bridge between tun0 and wlan0 is made when the vpn connection is created then the two interfaces are already connected.  So now, as you said, I miss the bridge between tun0 and eth0.  What do I have to do to do this?

**Comment by marcocondrache** [comment]
Another thing, tun0 has a metric of 0 so all internet traffic is directed to that interface

**Comment by arpitjindal97** [comment]
you can look at code in script, where bridging is done, just try to copy the same code paste it same place just below existing and replace the interfaces

**Comment by marcocondrache** [comment]
@arpitjindal97 ok I’ve resolved with your method
