### ISSUE TITLE
Compatibility Raspbian 11/Bullseye

### ISSUE THREAD

**Issue by stempst0r** [arpitjindal97/raspbian-recipes#56]
On Raspian 11 "iptables" isn't installed by default. The scripts highly relay on routings rules configured with iptables.

Simply add "sudo apt get iptables" to your README.md and compatibility is granted with latest os.

Successfully use "eth-to-wifi-route.sh" on raspi 4 with Raspbian 11.

**Comment by arpitjindal97** [comment]
Would you mind raising a small PR for it?

**Comment by stempst0r** [comment]
Did the PR :)
