### ISSUE TITLE
Mention that iptables needs to be installed as well

### ISSUE THREAD

**Issue by Herohtar** [arpitjindal97/raspbian-recipes#60]
It would be useful to mention that `iptables` also needs to be installed, as it is not always (or ever?) present by default.

https://github.com/arpitjindal97/raspbian-recipes/blob/7b4cce9290e4b62329426f8d6274739f01a28dcf/wifi-to-eth-bridge.sh#L13-L16

**Comment by nadafsak** [comment]
+1

**Comment by Herohtar** [comment]
This appears to have been resolved by #61 and #62
