### ISSUE TITLE
Adding -e fixed issue with wifi-to-eth-route.sh

### ISSUE THREAD

**Issue by mickeypash** [arpitjindal97/raspbian-recipes#63]
Thank you for the extremely helpful [blog post](https://www.instructables.com/Share-WiFi-With-Ethernet-Port-on-a-Raspberry-Pi/)

I don't know if this is just an issue with me but I was having issues with connectivity after using the script.
It took me quite some time to find it 🦭  but I think it was the fact that without the `-e` flag on the echo command the `\n` were not being rendered correctly and thus the `dnsmasq.conf` was not being applied?

```
echo -e "interface=$eth
bind-interfaces
server=$dns_server
domain-needed
bogus-priv
dhcp-range=$dhcp_range_start,$dhcp_range_end,$dhcp_time" > /tmp/custom-dnsmasq.conf
```

**Comment by arpitjindal97** [comment]
Can you create a PR for the fix ? Make sure to test if the conf file is generated properly with correct values
